import { json, requireSession, runtimeEnv, slugify } from "../../../../lib/server";
export const dynamic = "force-dynamic";
const editable = ["name","eyebrow","pageTitle","pageMessage","ctaText","giftTitle","giftMessage","accentColor","instagramText"] as const;
const columns: Record<string,string> = { name:"name", eyebrow:"eyebrow", pageTitle:"page_title", pageMessage:"page_message", ctaText:"cta_text", giftTitle:"gift_title", giftMessage:"gift_message", accentColor:"accent_color", instagramText:"instagram_text" };

export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try { const session = await requireSession(request); const { id } = await params; const event = await runtimeEnv.DB.prepare("SELECT id, slug, status, name, eyebrow, page_title as pageTitle, page_message as pageMessage, cta_text as ctaText, gift_title as giftTitle, gift_message as giftMessage, accent_color as accentColor, cover_image_key as coverImageKey, gift_image_key as giftImageKey, instagram_image_key as instagramImageKey, instagram_text as instagramText FROM events WHERE id = ? AND owner_id = ?").bind(id, session.user.id).first(); if (!event) return json({ error:"Presente não encontrado." },404); const sponsors = await runtimeEnv.DB.prepare("SELECT id, name, tier, tagline, logo_key as logoKey, position FROM sponsors WHERE event_id = ? ORDER BY position").bind(id).all(); return json({ ...event, sponsors:sponsors.results }); } catch(error){ return error instanceof Response?error:json({error:"Falha ao carregar."},500); }
}
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try { const session=await requireSession(request); const {id}=await params; const body=await request.json() as Record<string,unknown>; const sets:string[]=[]; const values:unknown[]=[]; for(const key of editable){if(typeof body[key]==="string"){sets.push(`${columns[key]} = ?`); values.push((body[key] as string).trim());}} let savedSlug:string|undefined;if(typeof body.slug==="string"){savedSlug=slugify(body.slug);const duplicate=await runtimeEnv.DB.prepare("SELECT id FROM events WHERE slug=? AND id!=?").bind(savedSlug,id).first();if(duplicate)return json({error:"Este endereço já está sendo usado por outra página."},409);sets.push("slug = ?");values.push(savedSlug);} if(!sets.length)return json({ok:true}); sets.push("updated_at = ?");values.push(Date.now(),id,session.user.id); const result=await runtimeEnv.DB.prepare(`UPDATE events SET ${sets.join(", ")} WHERE id = ? AND owner_id = ?`).bind(...values).run(); if(!result.meta.changes)return json({error:"Presente não encontrado."},404); return json({ok:true,slug:savedSlug}); } catch(error){return error instanceof Response?error:json({error:"Não foi possível salvar."},500);}
}
export async function DELETE(request: Request,{params}:{params:Promise<{id:string}>}){try{const session=await requireSession(request);const{id}=await params;await runtimeEnv.DB.prepare("DELETE FROM events WHERE id=? AND owner_id=?").bind(id,session.user.id).run();return json({ok:true});}catch(error){return error instanceof Response?error:json({error:"Não foi possível excluir."},500);}}
